### ISSUE TITLE
generic typedef

### ISSUE THREAD

**Issue by BigEpsilon** [nim-lang/c2nim#105]
The following code : 

    template <typename T>
    class Foo {
    public:
      typedef T BaseType;
    };
is translated to:

    type
      Foo* {.bycopy.}[T] = object
      
      BaseType* = T

Which is clearly invalid.

And typedef typename is not supported

I'm preparing a PR to solve this issue.

**Comment by Araq** [comment]
Now fixed thanks to your PR.
