### ISSUE TITLE
Wrong constructors for generic classes

### ISSUE THREAD

**Issue by BigEpsilon** [nim-lang/c2nim#111]
The following code:

    template <typename T>
    class Foo {
    public:
            Foo(){};
    };

is translated to:

    type
      Foo* {.importcpp: "Foo", header: "gconstructor.hpp", bycopy.}[T] = object

    proc constructFoo*[T](): Foo[T] {.constructor, importcpp: "Foo(@)",
                                   header: "gconstructor.hpp".}

Which cannot be used as the constructor Foo misses the template argument.

Instead it should be:

    proc constructFoo*[T](): Foo[T] {.constructor, importcpp: "Foo<\'*0>(@)",
                                       header: "gconstructor.hpp".}

**Comment by Araq** [comment]
Works now.
