### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by BigEpsilon** [nim-lang/c2nim#112]
With the head version of the compiler, c2nim fails to build with the following error:

     ... c2nim.nim(87, 17) Error: type mismatch: got (PNode, string)
     ... but expected one of:
     ... proc renderModule(n: PNode; infile, outfile: string; renderFlags: TRenderFlags = {})

after correcting this compilation errors, some tests fail because of some changes in the rendering process.

**Comment by Nazariglez** [comment]
Seems it's failing yet:

```c2nim.nim(87, 17) Error: type mismatch: got (PNode, string, string)
but expected one of: 
proc renderModule(n: PNode; filename: string; renderFlags: TRenderFlags = {})
```
