### ISSUE TITLE
c2nim fails to compile

### ISSUE THREAD

**Issue by Florin65** [nim-lang/c2nim#121]
HI,
I have a functional nim and nimble install.
The compile of c2nim fails. Here is the comple log:

++ Mark Compile start  : "c2nim" "git" "Wed, 24 Jan 2018 06:43:20 +0000"
[33m[1m   Warning: [0m[33m[0mPackage 'c2nim' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'c2nim.nim', but a file named 'cparse.nim' was found. This will be an error in the future.
[33m[1m      Hint: [0m[33m[0mIf this is the primary source file in the package, rename it to 'c2nim.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'c2nim', then move it into a 'c2nimpkg/' subdirectory. If it's a test file or otherwise not required to build the the package 'c2nim.nim', prevent its installation by adding `skipFiles = @["cparse.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
[36m[1m  Verifying [0m[36m[0mdependencies for c2nim@0.9.13
[36m[1m      Info: [0m[36m[0mDependency on compiler@>= 0.16.0 already satisfied
[36m[1m  Verifying [0m[36m[0mdependencies for compiler@0.17.2
[36m[1m   Building [0m[36m[0mc2nim/c2nim using c backend
[33m[1m       Tip: [0m[33m[0m2 messages have been suppressed, use --verbose to show them.
[31m[1m     Error: [0m[31m[0mBuild failed for package: c2nim
[31m[1m        ... [0m[31m[0mDetails:
[31m[1m        ... [0m[31m[0mExecution failed with exit code 1
[31m[1m        ... [0m[31m[0mCommand: "/usr/bin/nim" c --noBabelPath --path:"/root/.nimble/pkgs/compiler-0.17.2"  -o:"/usr/src/c2nim-git/c2nim" "/usr/src/c2nim-git/c2nim.nim"
[31m[1m        ... [0m[31m[0mOutput: Hint: used config file '/etc/nim.cfg' [Conf]
[31m[1m        ... [0m[31m[0mHint: system [Processing]
[31m[1m        ... [0m[31m[0mHint: c2nim [Processing]
[31m[1m        ... [0m[31m[0mHint: strutils [Processing]
[31m[1m        ... [0m[31m[0mHint: parseutils [Processing]
[31m[1m        ... [0m[31m[0mHint: math [Processing]
[31m[1m        ... [0m[31m[0mHint: algorithm [Processing]
[31m[1m        ... [0m[31m[0mHint: os [Processing]
[31m[1m        ... [0m[31m[0mHint: times [Processing]
[31m[1m        ... [0m[31m[0mHint: posix [Processing]
[31m[1m        ... [0m[31m[0mHint: ospaths [Processing]
[31m[1m        ... [0m[31m[0mHint: parseopt [Processing]
[31m[1m        ... [0m[31m[0mHint: llstream [Processing]
[31m[1m        ... [0m[31m[0mHint: ast [Processing]
[31m[1m        ... [0m[31m[0mHint: msgs [Processing]
[31m[1m        ... [0m[31m[0mHint: options [Processing]
[31m[1m        ... [0m[31m[0mHint: strtabs [Processing]
[31m[1m        ... [0m[31m[0mHint: hashes [Processing]
[31m[1m        ... [0m[31m[0mHint: osproc [Processing]
[31m[1m        ... [0m[31m[0mHint: streams [Processing]
[31m[1m        ... [0m[31m[0mHint: cpuinfo [Processing]
[31m[1m        ... [0m[31m[0mHint: linux [Processing]
[31m[1m        ... [0m[31m[0mHint: sets [Processing]
[31m[1m        ... [0m[31m[0mHint: tables [Processing]
[31m[1m        ... [0m[31m[0mHint: ropes [Processing]
[31m[1m        ... [0m[31m[0mHint: platform [Processing]
[31m[1m        ... [0m[31m[0mHint: terminal [Processing]
[31m[1m        ... [0m[31m[0mHint: macros [Processing]
[31m[1m        ... [0m[31m[0mHint: termios [Processing]
[31m[1m        ... [0m[31m[0mHint: nversion [Processing]
[31m[1m        ... [0m[31m[0mHint: securehash [Processing]
[31m[1m        ... [0m[31m[0mHint: idents [Processing]
[31m[1m        ... [0m[31m[0mHint: wordrecg [Processing]
[31m[1m        ... [0m[31m[0mHint: intsets [Processing]
[31m[1m        ... [0m[31m[0mHint: idgen [Processing]
[31m[1m        ... [0m[31m[0mHint: renderer [Processing]
[31m[1m        ... [0m[31m[0mHint: lexer [Processing]
[31m[1m        ... [0m[31m[0mHint: nimlexbase [Processing]
[31m[1m        ... [0m[31m[0mHint: clex [Processing]
[31m[1m        ... [0m[31m[0mHint: cparse [Processing]
[31m[1m        ... [0m[31m[0mHint: pegs [Processing]
[31m[1m        ... [0m[31m[0mHint: unicode [Processing]
[31m[1m        ... [0m[31m[0mHint: astalgo [Processing]
[31m[1m        ... [0m[31m[0mHint: rodutils [Processing]
[31m[1m        ... [0m[31m[0mHint: postprocessor [Processing]
[31m[1m        ... [0m[31m[0mc2nim.nim(87, 17) Error: type mismatch: got (PNode, string, string)
[31m[1m        ... [0m[31m[0mbut expected one of: 
[31m[1m        ... [0m[31m[0mproc renderModule(n: PNode; filename: string; renderFlags: TRenderFlags = {})
++ Mark Compile stop   : "c2nim" "git" "Wed, 24 Jan 2018 06:43:22 +0000"

**Comment by dom96** [comment]
Might be related to this: https://github.com/nim-lang/c2nim/issues/115
