### ISSUE TITLE
c2nim converts const into vars

### ISSUE THREAD

**Issue by genotrance** [nim-lang/c2nim#123]
```c++
const int test = 1;
typedef int arr[test];

int main() { }
```
Becomes:
```nim
var test*: cint = 1

type
  arr* = array[test, cint]

proc main*(): cint =
  discard
```
Compile fails though:
```test.nim(4, 16) Error: cannot evaluate at compile time: test```

If test was converted into a const, it works.

Using c2nim 0.9.13 on Windows with Nim #head.

**Comment by Araq** [comment]
c2nim could inline the literal here for array declaration. It needs to stay a var as that is closer to C++'s notion of ``const int`` (you can cast the constness away etc)
