### ISSUE TITLE
c2nim generates variable names which are nim keywords, code then fails to compile in nim

### ISSUE THREAD

**Issue by genotrance** [nim-lang/c2nim#126]
```c++
const int test = 1;
typedef int array[test];
```
becomes
```nim
var test*: cint = 1

type
  array* = array[test, cint]
```
which doesn't compile due to #123 which is secondary here. Even if we make it const test*, it fails since array is a special keyword.

```test.nim(4, 17) Error: no generic parameters allowed for array```

Changing array* into arr*, nim compiles fine.

**Comment by Araq** [comment]
"array" is not a keyword though.
