### ISSUE TITLE
c2nim should rename _t types

### ISSUE THREAD

**Issue by genotrance** [nim-lang/c2nim#133]
For example `uint32_t` is the same as `uint32` in Nim but many C libs use the `_t` suffix and this results in unknown type errors. C2nim should detect these and rename on the fly. It could be done in `nimgen` but considering many people use c2nim directly, it's better implemented here.

**Comment by Araq** [comment]
``#mangle`` not good enough?

**Comment by genotrance** [comment]
#mangle is cool but requires effort on part of user to do it. For this common use case, c2nim could just  handle this automatically.

I can always leverage #mangle or other ways within nimgen to do this but direct users of c2nim won't benefit.

If this isn't deemed too useful, we can close.

**Comment by Araq** [comment]
Nah it's cool, can't be hard to implement.

**Comment by data-man** [comment]
I can't understand: we have ```--prefix:``` and ```--suffix:```.

**Comment by genotrance** [comment]
@data-man verified that `--suffix` works for this. I'd still like `c2nim` to do it by default so that it just happens but it's easy to manage this. Use `--suffix`, `#mangle` or nimgen can also do a regex replace:

```
regex = """([u]int[\d]+)_t"""
replace = "$1"
```

**Comment by Araq** [comment]
We nowadays have the `--nep1` switch which works really well IME.
