### ISSUE TITLE
All tests fail on windows because git changes line endings to CRLF

### ISSUE THREAD

**Issue by nc-x** [nim-lang/c2nim#144]
If git is configured to `Checkout Windows-style, commit Unix-style` which is the recommended way on Windows AFAIK, then the tests fail because [expected results](https://github.com/nim-lang/c2nim/tree/3ec45c24585ebaedbbe2f05d9312f633abdd30fc/testsuite/results) now have an additional CRLF in them.
  
Maybe it would be better for the tests to be checked for compile and runtime errors instead?

**Comment by Araq** [comment]
"Checkout Windows-style" is not what I've seen recommended anywhere ever.

**Comment by nc-x** [comment]
It is recommended (and is the default) in the Git Installer -
![untitled](https://user-images.githubusercontent.com/43749640/47897795-1ba59880-de99-11e8-9428-ec36e17a3002.png)
  
In any case, I created a PR for adding .gitattributes.
