### ISSUE TITLE
Segfault on std::vector construction

### ISSUE THREAD

**Issue by mratsim** [nim-lang/c2nim#146]
The following C++ snippet will crash c2nim with SIGSEGV: Illegal storage access:

```C++
#include <cstdint>
#include <vector>

int main(){
  std::vector<int64_t> foo(10);
  return 0;
}
```

**Comment by StefanSalewski** [comment]
Unfortunately c2nim crashes very often when scope operator :: is found like in myCppHeader::myfunction() or in this basic example:

```
#include <iostream>

int main()
{
  std::cout << "Hello World!";
}
```

For a test I have just deleted all occurrences of :: and converted some rare initializers like "std::vector<int64_t> foo(10)" to plain "stdvectorint64_t foo". So c2nim produced some partly useful Nim code, which save me a lot of typing when converting some cpp to Nim.

**Comment by Araq** [comment]
I can reproduce and it's hard to fix. :-)

**Comment by cheatfate** [comment]
Maybe it crashes because it called `c2nim` not `cpp2nim`?
