### ISSUE TITLE
Error: did not expect {

### ISSUE THREAD

**Issue by kitech** [nim-lang/c2nim#154]
Only need one line to  produce:

test.h: from nng.h

`
#define NNG_PIPE_INITIALIZER { 0 }
`

```
$ c2nim -V
0.9.14
```

**Comment by genotrance** [comment]
While c2nim gets fixed, you can find a working nng wrapper [here](https://github.com/genotrance/feud/blob/master/wrappers/nng.nim). It uses nimterop though and compiles in the code rather than using a DLL.

**Comment by kitech** [comment]
That's seems nice. Try it.
It's better push to nimble package list.

**Comment by Araq** [comment]
Use ``#defi NNG_PIPE_INITIALIZER { 0 }`` and read c2nim's manual.

**Comment by kitech** [comment]
Thanks any way.
But it's bad if need modify C code to invalid C code.

**Comment by Araq** [comment]
There are also other solutions, outlined in the manual.
