### ISSUE TITLE
Token expected: ;

### ISSUE THREAD

**Issue by mantielero** [nim-lang/c2nim#158]
While processing [unzip.h](https://github.com/madler/zlib/blob/master/contrib/minizip/unzip.h) I get:
```
$ c2nim unzip.h 
/home/jose/src/nimlang/minizip/zlib-1.2.11/contrib/minizip/unzip.h(153, 44) Error: token expected: ;
```

So it is complainining at this point:
```
                                           ▼
extern int ZEXPORT unzStringFileNameCompare OF ((const char* fileName1,
                                                 const char* fileName2,
                                                 int iCaseSensitivity));
```

Is it a bug or is there something that I can do?

Kind regards and thanks for this effort

**Comment by Araq** [comment]
```
#def ZEXPORT
#def OF(x) x
```

See https://github.com/nim-lang/c2nim/blob/master/doc/c2nim.rst#def-directive
