### ISSUE TITLE
In header mode, function body should be ignored

### ISSUE THREAD

**Issue by ratiotile** [nim-lang/c2nim#164]
If I'm trying to generate a wrapper, I don't care if the entire function definition is in the header file. In header mode, c2nim should ignore everything between after the function declaration between `{` and `}`. This prevents the parser from choking on things it does not understand but it can simply skip over.

**Comment by Araq** [comment]
That doesn't seem to be too useful for "inline" functions. Besides now c2nim can extract Nim code even if the code has constructs that c2nim doesn't understand.
