### ISSUE TITLE
Support C++11 attributes

### ISSUE THREAD

**Issue by ratiotile** [nim-lang/c2nim#166]
An {attribute specifier sequence](https://en.cppreference.com/w/cpp/language/attributes) is surrounded by double square brackets like this: `[[gnu::always_inline, gnu::const, gnu::hot, nodiscard]]`. The simplest thing for c2nim to do is ignore these, or to turn them into comments. Certain attributes like nodiscard, noreturn, or deprecated may have nim pragma analogs.

**Comment by Araq** [comment]
This has been implemented.
