### ISSUE TITLE
Parameter names using reserved keywords generate bad nim code

### ISSUE THREAD

**Issue by gradha** [nim-lang/c2nim#17]
The following header:
```c
void *hoedown_realloc(void *ptr, int size) ;
```
will generate the following nim file:
```nimrod
proc hoedown_realloc*(ptr: pointer; size: cint): pointer
```
This won't compile because ``ptr`` is a reserved keyword. It can be solved by quoting the name or mangling it (say, add the letter ``c``).

**Comment by Araq** [comment]
This has been implemented.
