### ISSUE TITLE
Nimble install fails

### ISSUE THREAD

**Issue by matkuki** [nim-lang/c2nim#170]
Installing `c2nim` with `nimble install c2nim` fails with:
```
Downloading https://github.com/nim-lang/c2nim using git
  Verifying dependencies for c2nim@0.9.14
      Info: Dependency on compiler@>= 0.18.0 already satisfied
  Verifying dependencies for compiler@#head
 Installing c2nim@0.9.14
   Building c2nim/c2nim.exe using c backend
       Tip: 3 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: c2nim
        ... Details:
        ... Execution failed with exit code 1
        ...
        ..\.nimble\pkgs\compiler-#head\compiler\packagehandling.nim(43, 13) Error: usage of 'isNil' is a user-defined error
```
Specs:
- Windows 10
- Nim Compiler Version 0.20.99 [Windows: amd64]

**Comment by tajmone** [comment]
Strange, I've installed it yesterday and it went fine. Using Nim 0.20.0 on Win 10 Home x64.

**Comment by genotrance** [comment]
Looks like a compiler bug, probably fixed so you might want to try again.

Cc @narimiran

**Comment by matkuki** [comment]
Just tried a fresh Nim install from source, so now I have:
```
Nim Compiler Version 0.20.99 [Windows: amd64]
Compiled at 2019-07-15
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: ad67a46e5ddcf260281b13b79bf50afa779b234d
active boot switches: -d:release
```
and Nimble:
```
nimble v0.10.2 compiled at 2019-07-15 10:17:58
git hash: d15c8530cb7480ce39ffa85a2dd9819d2d4fc645
```
Still the same error appears.

**Comment by imandicdev** [comment]
(using nimble on WIn10 Pro)
Tried to install c2nim via nimble, tried different versions but it failed, at the end added a switch --cpu:i386 --os:windows and it worked for me.

nimble install c2nim@#head --cpu:i386 --os:windows

**Comment by Araq** [comment]
Now works again.
