### ISSUE TITLE
c2nim Enforces LF EOL on Windows

### ISSUE THREAD

**Issue by tajmone** [nim-lang/c2nim#171]
I'm not sure whether this is intended or not — and not even sure whether the convention for `.nim` source files is to use native EOLs or always LF.

In any case, files generated by c2nim under Windows OS have Unix-like EOLs (`LF`). When I automate headers conversions in a repository, where I usually set Git to normalize Nim sources to native EOLs, I then have to either fix the EOL in the generated Nim files via the unix2dos tool, or create a special `.gitattributes` rule for the auto-generated files.

IMO, it would make sense to enforce native EOLs, or at least supply a CLI option to choose which EOL to use in the generated files.

Does it make sense? or am I missing out something about EOL conventions in Nim?

**Comment by Araq** [comment]
The EOL convention is LF-everywhere indeed. And git should always be configured to "don't touch the newlines" anyway, how else can you write tests that contain CR-LF on Linux?

**Comment by tajmone** [comment]
> The EOL convention is LF-everywhere indeed. 

Thanks @Araq, good to know! Some editors just assume native EOL (e.g. Sublime Text with Nim-Lime package). I'll edit the configuration in all editors to always enforce `LF`.

> how else can you write tests that contain CR-LF for Linux?

Git only normalizes EOLs at checkout, so all files would still be stored with `LF` in the repository index, but converted to `CRLF` locally on Windows machines (only) — and only if set to native EOL, or by default if no EOL is specified under Git for Windows.

**Comment by tajmone** [comment]
@Araq, I guess then that using LF everywhere applies to all Nim-related source files (project/file compiler settings, packages, scripts, etc.). Could you confirm that please?

**Comment by Araq** [comment]
Confirmed. However, just to be clear about this: On every supported plaform Nim also understands CR-LF.

**Comment by tajmone** [comment]
Thanks. I'm asking all these details because I'm working on a [GitHub repository-template] for Nim, which allows quick creation of new repositories via a boilerplate with some useful Git configuration presets.

The EOL issue on Git repositories and Windows OS is always a but tricky.
On the one hand, if you don't set correct EOL normalization settings in `.gitattributes`, and a Windows user with bad local Git configuration contributes material, the risk is that he/she might push source files with `CRLF` EOLs, which then becomes a problem for Linux and macOS users.

On the other hand, the Bash for Windows that ships with Git tends to use native OS EOLs, except that some native tools (like SED) use `LF`, and native Windows tools (which might be invoked from Bash scripts too) always output `CRLF` EOLs.

So, having the correct settings in `.gitattributes` is important, to dispel any conflicts with the repository expectation and the local Git and editor settings. Needless to say, this is a general problem with many languages, and not Nim specific in any way.

It would be good to add to Nim Manual (or the style guide) a few notes on EOL best practices IMO, to avoid proliferation of confusion on this issue (already many editors extensions adopt different EOLs on Windows OS).



[GitHub repository-template]: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

**Comment by tajmone** [comment]
@Araq, here's the repository template I was talking about:

https://github.com/tajmone/nim-repository-template

I hope this might be useful for Nim beginners (like me).
