### ISSUE TITLE
Use non-deprecated "union" pragma location

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/c2nim#174]
For bycopy unions, we want the pragmas changed everywhere:
```
-  INNER_C_UNION_hts_concat_212* {.bycopy.} = object {.union.}
+  INNER_C_UNION_hts_concat_212* {.bycopy, union.} = object
```
The old style is deprecated here:
* https://nim-lang.org/blog/2019/06/06/version-0200-released.html
> Pragma syntax is now consistent. Previous syntax where type pragmas did not follow the type name is now deprecated.... See nim-lang/Nim#8514 ... for further details.
* https://github.com/brentp/hts-nim/pull/44

**Comment by Araq** [comment]
This has been implemented.
