### ISSUE TITLE
Compiler needs to be synced with nim compiler

### ISSUE THREAD

**Issue by foldl** [nim-lang/c2nim#177]
I have encounter with an issue in the converting of hex value in C.

After digging into the code, it is caused by `let y = x and ((1 shl (size*8)) - 1)`  in renderer.nim, when
compiled against 32-bit platform.

In the newest nim compiler, this line has been deleted. So, I think c2nim needs an update and get
in sync with current nim compiler.

**Comment by Araq** [comment]
Hex values are now kept as they are anyway.
