### ISSUE TITLE
Array error

### ISSUE THREAD

**Issue by cloud42** [nim-lang/c2nim#18]
//======== c code =========   
 const GLfloat diamond[4][2] = {
    {  0.0,  1.0  }, // Top point 
    {  1.0,  0.0  }, // Right point 
    {  0.0, -1.0  }, // Bottom point 
    { -1.0,  0.0  } }; // Left point 

//======== will be nim code =======
var cc: array[2, array[4, float]] = [[0.0, 1.0], [1.0, 0.0], 
      [0.0, - 1.0], [- 1.0, 0.0]]

hello.nim(7, 36) Error: type mismatch: got (Array constructor[0..3, Array constructor[0..1, float]]) but expected 'array[0..1, array[0..3, float]]'

**Comment by fowlmouth** [comment]
the type of `cc` should be `array[4, array[2, float]]`
