### ISSUE TITLE
size_t should be replaced by uint, not csize

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/c2nim#181]
Since this tool is being used to interface with C and C++ libraries, we can't afford that whole "we'll change the C standard in our leaky abstraction" silliness, so what is an unsigned integer in C should be the same in the Nim wrapper.

Relevant Nim silliness: https://github.com/nim-lang/Nim/issues/12187

**Comment by Araq** [comment]
Don't we have ``csize_t`` now in system.nim we can use instead?

**Comment by stefantalpalaru** [comment]
Yes, csize_t will be just as good, once it reaches a release.

**Comment by Araq** [comment]
Now uses `csize_t`.
