### ISSUE TITLE
'ident' is not accessible using discriminant 'kind' of type 'TNode'

### ISSUE THREAD

**Issue by dariolah** [nim-lang/c2nim#182]
Code generated by c2nim fails to compile with nim 1.2:

> Error: unhandled exception: 'ident' is not accessible using discriminant 'kind' of type 'TNode' [FieldError]

Sample code is attached

[sample_code.zip](https://github.com/nim-lang/c2nim/files/4432168/sample_code.zip)

**Comment by Araq** [comment]
This is a Nim bug and has been resovled, now the Nim compiler says:

> iup_concat.nim(32, 3) Error: invalid type: 'template (s: untyped): untyped' for const. Did you mean to call the template with '()'?
