### ISSUE TITLE
nimble can't install c2nim for latest stable nim compiler (v0.10.2)

### ISSUE THREAD

**Issue by lou15b** [nim-lang/c2nim#19]
Commit `1625c5ab77` changed the nim compiler dependency in `c2nim.nimble` to `>=0.10.3`, which currently specifies the development/unstable branch of nim. The impact of this is that anyone with the latest stable nim release (version 0.10.2) cannot install c2nim using nimble because the package's compiler dependency is violated.

According to my understanding of the way nimble works, the way to address this problem is to tag the c2nim commit immediately preceding `1625c5ab77`, which I believe is `ffdb350b4f`, where the compiler dependency is `>=0.10.2`. Since that would be the only tag for c2nim, nimble would pick up that version by default. Anyone wishing to pick up the latest c2nim commit would still be able to do so by telling nimble to install from `HEAD`.

**Comment by yglukhov** [comment]
I cannot install it with devel compiler as well.
```
$ nimble install c2nim                                                                                                              (04d85bf✱) 
Downloading c2nim into /tmp/nimble_1044/c2nim using git...
Cloning into '/tmp/nimble_1044/c2nim'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 38 (delta 0), reused 20 (delta 0), pack-reused 0
Receiving objects: 100% (38/38), 52.44 KiB | 0 bytes/s, done.
Checking connectivity... done.
Looking for nim (>= 0.10.3)...
None found, installing...
nim not found in local packages.json, check internet for updated packages? [y/N]
y
Downloading package list from https://github.com/nimrod-code/packages/raw/master/packages.json
Done.
FAILURE: Package not found.
```

**Comment by akozadaev** [comment]
+1
I'm wondering if there is a technical reason to keep such dependency? Does it even work with 0.10.2?
This is a setback for people trying to use FFI, like myself.

**Comment by yglukhov** [comment]
Actually I was able to install it fine after updating nimble. Something like ```nimble install nimble```.

**Comment by akozadaev** [comment]
hmm... are you sure you're still on 0.10.2 (not on devel)? It definitely does NOT work for me.

**Comment by yglukhov** [comment]
Right, sorry, I'm on devel. What's the point of not using devel anyway? ;)

**Comment by akozadaev** [comment]
not brave enough... hehehe.. Thanks for confirming. I'll try upgrading to devel.

**Comment by lazypenguin** [comment]
Just installed using nimble dev and nim v0.14

**Comment by dom96** [comment]
Assuming this can now be closed.
