### ISSUE TITLE
deadCodeElim-pragma should not start with a space

### ISSUE THREAD

**Issue by def-** [nim-lang/c2nim#20]
The deadCodeElim pragma is always indented with a single space. This fails to compile if it's not at the start of the file.

**Comment by def-** [comment]
This is the space that causes the issue: https://github.com/Araq/Nim/blob/devel/compiler/renderer.nim#L1193

Usually it's fine, but not when at the top of the file.

**Comment by Araq** [comment]
The renderer has been fixed.
