### ISSUE TITLE
Unknown Unicode symbols in comments cause c2nim to freeze 

### ISSUE THREAD

**Issue by GavinRay97** [nim-lang/c2nim#206]
The `` character here when removed allows a 5,000 line header to be parsed/converted, but when present will cause the program to hang indefinitely with no output:

![image](https://user-images.githubusercontent.com/26604994/113523067-ac559680-9573-11eb-8f16-0c0062d97be2.png)

![CNGRPWUSU3](https://user-images.githubusercontent.com/26604994/113523043-862ff680-9573-11eb-8ddd-981b1614316f.gif)

**Comment by Araq** [comment]
Cannot reproduce, works for me.
