### ISSUE TITLE
replace travis-ci with Github Action

### ISSUE THREAD

**Issue by xflywind** [nim-lang/c2nim#209]
travis-ci should be removed which is dead, instead we should use github action.

Ref Vindaar/ggplotnim#104

Travis CI is no longer providing CI minutes for open source projects

see https://news.ycombinator.com/item?id=25338983

As we can see, the CI doesn't work since 9 Feb

see also https://github.com/nim-lang/nimforum/pull/281

**Comment by Araq** [comment]
Done.
