### ISSUE TITLE
anonymous structs members of a typedef struct end up with the same name

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/c2nim#217]
Consider this example:
```c
typedef struct
{
    struct
    {
        struct
        {
            int a;
        } meow;
    } meow2;
} miauz;
```
c2nim generates this code for it:
```nim
type
  INNER_C_STRUCT_nestedanonymousstruct_11* {.bycopy.} = object
    a*: cint

  INNER_C_STRUCT_nestedanonymousstruct_11* {.bycopy.} = object
    meow*: INNER_C_STRUCT_nestedanonymousstruct_11

  miauz* {.bycopy.} = object
    meow2*: INNER_C_STRUCT_nestedanonymousstruct_11
```

I figured out that this is because of the [backtracking](https://github.com/nim-lang/c2nim/blob/master/cparser.nim#L1361-L1372) and I could fix it somehow, though everything I can come up with would be a bit invasive and a bit dirty. So any suggestions how to approach this?

**Comment by Araq** [comment]
Just change the name generation for anon structs, it could use some counter, doesn't look hard, why would it be invasive?

**Comment by RSDuck** [comment]
> Just change the name generation for anon structs, it could use some counter, doesn't look hard, why would it be invasive?

I wanted to avoid that for compability, my thoughts mostly gathered around getting the line number reliably during backtracking. Though if changing the enumeration is acceptable I'll do just that.
