### ISSUE TITLE
fails to recognise stdint types

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/c2nim#240]
types like `uint64_t` and friends have direct correspondents in Nim (`uint64`) - this should be recognised and translated accordingly.

**Comment by elcritch** [comment]
This is possible with the mangle option that was merged recently: `--mangle:'{u?}int{\d+}_t=$1int$2'`. 

However, my new PR includes a `--stdints` to set this up automatically. See: https://github.com/nim-lang/c2nim/pull/251

**Comment by elcritch** [comment]
@Araq I believe this can be closed now with #251.
