### ISSUE TITLE
Trailing whitespace on on const, type, object, enum keywords

### ISSUE THREAD

**Issue by gmpreussner** [nim-lang/c2nim#27]
Possibly other keywords as well. There should be no trailing whitespaces before line breaks.

**Comment by gmpreussner** [comment]
I noticed that it always creates extra whitespaces, for example:

```nimrod
type
  foo* = object  {.union.}
```

Notice two whitespaces between 'object' and '{.union.}'

**Comment by Araq** [comment]
Well it's easier to generate code this way, but surely we can run a postprocessing step or fix the renderer.

**Comment by Araq** [comment]
The renderer has been fixed.
