### ISSUE TITLE
cpp.nim(88, 41) Error: undeclared identifier: 'TMacro'

### ISSUE THREAD

**Issue by Stryzhevskyi** [nim-lang/c2nim#37]
I can't install c2nim :
```bash
$ nim --v
Nim Compiler Version 0.11.3 (2015-06-20) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 49745248545e0a751c37293fd68e34d95596d455
active boot switches: -d:release
$ nimble --v
nimble v0.6.2 compiled at 2015-06-20 02:49:10

$ nimble install c2nim > ~/nimble.log
```
[nimble.log](http://pastebin.com/raw.php?i=LY75y1NX)

Thank you

**Comment by Airr** [comment]
In a commit dated June 9, some of the "T" prefixes were removed.

So I tried replaced instances of "TMacro" with "Macro", and "TParser" with "Parser" in my local cpp.nim and it compiled.
