### ISSUE TITLE
Unable to translate working code

### ISSUE THREAD

**Issue by paintenzero** [nim-lang/c2nim#39]
I took source files from https://bitbucket.org/geekman/tinysvcmdns compiled and checked it works. Then tried to translate sources to nim-lang and got errors:
```
$ c2nim mdnsd.c
mdnsd.c(641, 45) Error: identifier expected, but found '*'
$ c2nim mdns.c 
mdns.c(380, 7) Error: did not expect [NewLine]
```

**Comment by Araq** [comment]
Well it helps to read the c2nim docs.

**Comment by paintenzero** [comment]
I know you are smart but could you explain?

**Comment by Araq** [comment]
Well you need to tweak the C code until c2nim likes it. c2nim gets more and more things right, but it's still quite stupid at times. From http://nim-lang.org/docs/c2nim.html: 

> c2nim cannot parse all of Ansi C

**Comment by Varriount** [comment]
In particular, many macros that c2nim can't translate into Nim templates must have their `#define` replaced with `#def`, or be removed from a file.

**Comment by Varriount** [comment]
Also, you usually run c2nim on header files/data declarations, not actual implementation code.
