### ISSUE TITLE
long const int *  parameter not parsed

### ISSUE THREAD

**Issue by jlp765** [nim-lang/c2nim#40]
C2Nim can not parse 
  `void   cdCanvasPattern(cdCanvas* canvas, int w, int h, long const int *pattern);`

output error is:  `Error: ')' expected`

but removing the const allows c2nim to parse the statement:
  `void   cdCanvasPattern(cdCanvas* canvas, int w, int h, long int *pattern);`

**Comment by Varriount** [comment]
That's actually valid C?

**Comment by jlp765** [comment]
Yes,

from the IUP CD (canvas drawing) library
