### ISSUE TITLE
Add translation-time calculated `#ifdef`'s

### ISSUE THREAD

**Issue by Varriount** [nim-lang/c2nim#45]
Just as c2nim has `#def`, which acts much like a preprocessor's `#define`, it would be convenient for c2nim to have a `#ifdef` which acts much like a preprocessor's.

In my particular case, I'm translating headers which have `#ifdef` sections that either contain c++ code, or non-standard C syntax extensions, which cause c2nim to error when translating. It's nontrivial to edit these sections away, as these header files can have 100+ instances.

**Comment by Varriount** [comment]
@Araq What would need to be done to add this?

**Comment by andreaferretti** [comment]
Should be done by https://github.com/nim-lang/c2nim/pull/86

**Comment by Araq** [comment]
Use something like:

```c


#assumedef bar

#ifdef bar
const int value = 0;
#endif
```
