### ISSUE TITLE
bitfields not implemented

### ISSUE THREAD

**Issue by tmm1** [nim-lang/c2nim#49]
``` c
struct bits {
  int flag:1;
  int opts:4;
};
```

```
c2nim/testsuite/tests/bitfield.h(2, 13) Error: ';' expected
```

**Comment by tmm1** [comment]
I have a patch to the parser that prevents it from blowing up on this struct, but I'm not sure what the emitted nim code should be. /cc @Araq

**Comment by Varriount** [comment]
I'm guessing type members should probably grow a "bitsize" pragma, once one is actually implemented.
