### ISSUE TITLE
add option to include common preamble

### ISSUE THREAD

**Issue by tmm1** [nim-lang/c2nim#51]
I'm using c2nim with ffmpeg, which contains 98 header files. I would like to avoid patching every file for c2nim consumption (and then have to maintain that patch), since most of the headers fail to parse with the same errors. For instance, all the headers include [`libavutil/attributes.h`](https://github.com/ffmpeg/ffmpeg/blob/master/libavutil/attributes.h) which defines macros like `attribute_deprecated` and `av_const` that are used throughout the rest of the code base:

``` c
attribute_deprecated void func();
int64_t av_const av_gcd(int64_t a, int64_t b);
void func2(int av_unused flags);
```

I'd like to be able to pass c2nim a file that it parses before parsing the supplied header:

```
$ cat > common.h <<EOS
#def av_unused
#def av_const
#def attribute_deprecated
EOS
$ c2nim --preamble common.h avcodec.h
```

**Comment by tmm1** [comment]
Looks like this already works with `c2nim --header common.h avcodec.h`

**Comment by tmm1** [comment]
The docs for the `--header` option are pretty confusing:

```
  --header:HEADER_FILE   import from a HEADER_FILE (discouraged!)
  --header               import from the given header file
```

**Comment by Araq** [comment]
You're supposed to use a c2nim configuration file instead. Please look at https://github.com/Araq/wxnim for an extensive example.

**Comment by tmm1** [comment]
Oh wow, I didn't see that mentioned anywhere. Thanks.
