### ISSUE TITLE
CPP function ptrs

### ISSUE THREAD

**Issue by jlp765** [nim-lang/c2nim#59]
function pointers in a Class fail to convert with error
`Error: identifier expected, but found '*'`
when converting (with `--cpp`)

```
class failClass {
public:
  void (*warning)(const char*, ...);    // <- this fails!!
  void *warning(const char*, ...);
};
```

**Comment by hcorion** [comment]
Yes please fix this! The title should be changed though, because it happens with both C and C++.

**Comment by GavinRay97** [comment]
Bumping this for visibility 5 years later:

```c
// simple-test.h
struct c2nim_test {
  void (*some_func)(int a, int b);
};
```
```sh-session
$ ./c2nim --cpp --debug --nep1 --out:file.nim ./simple-test.h
```

![image](https://user-images.githubusercontent.com/26604994/113521368-1156bf80-9567-11eb-93b3-031560105707.png)

Dropping the `--cpp` flag works though:

![image](https://user-images.githubusercontent.com/26604994/113521415-55e25b00-9567-11eb-8b0f-4d37141f9758.png)
