### ISSUE TITLE
c2nim not marking structs as {.pure.}

### ISSUE THREAD

**Issue by m13253** [nim-lang/c2nim#63]
C code:

``` c
struct Point {
    int x, y;
};
```

Converted Nim code:

``` nim
type
  Point* = object
    x*: cint
    y*: cint
```

According to [Nim Manual](http://nim-lang.org/docs/manual.html#pragmas-pure-pragma), an object type can be marked with the `{.pure.}` so that its type field which is used for RTTI is omitted. This used to be necessary for binary compatibility with other compiled languages.

I interpret the above sentence as: If you don't specify `{.pure.}`, the struct will not be ABI compatible with underlying C library, due to some RTTI features Nim might have.

Could you give me a reason, why `{.pure.}` is not added into converted Nim code? Or if it is necessary, could you add it?

**Comment by Araq** [comment]
.pure is simply not required anymore and c2nim knows this. Maybe we need to improve the manual to make it even more clear?

**Comment by m13253** [comment]
> pure is simply not required anymore and c2nim knows this

Thank you. Could you please update the manual?

**Comment by Varriount** [comment]
@Araq just out of curiosity, she isn't it required?

**Comment by andreaferretti** [comment]
It would be useful to add a directive to restore the old behaviour, though. Enums can become quite unwieldly, and keeping them pure is often useful (especially if trimming the prefix)

**Comment by Araq** [comment]
Not a problem anymore, the manual was updated.
