### ISSUE TITLE
c2nim docs: 404 Not Found

### ISSUE THREAD

**Issue by cdunn2001** [nim-lang/c2nim#65]
> c2nim is a tool to translate Ansi C code to Nim. The output is human-readable Nim code that is meant to be tweaked by hand before and after the translation process. http://nim-lang.org/c2nim.html

That link redirects to http://nim-lang.org/docs/c2nim.html which gives a 404 error. However, this one works:
- http://nim-lang.org/0.11.0/c2nim.html

**Comment by dom96** [comment]
Copied the old docs in there as a temporary fix.

**Comment by Araq** [comment]
The website now links to proper docs.
