### ISSUE TITLE
c2nim doesn't like using macro to declare imported symbol

### ISSUE THREAD

**Issue by hcorion** [nim-lang/c2nim#67]
I have a C/C++ header file that I would like to convert to nim. It uses __declspec (dllimport) to reference functions from a provided dll. The C code looks like this:

``` C
#ifndef LINUX
  #if !defined (AW_SDK) && !defined (AW_BROWSER) && !defined (AW_STATIC)
    #define AWAPI     __declspec (dllimport)
  #else
    #define AWAPI
  #endif
...
```

and later on in the code uses the AWAPI macro to declare each imported symbol:

``` C
AWAPI int   aw_sdk_build (void);
AWAPI int   aw_init (int build);
AWAPI int   aw_init_bind (int build, unsigned long Addr);
```

c2nim doesn't like doing this however, and complains: 

> aw.h(1330, 25) Error: ';' expected

The msdn documentation also recommends doing this: https://msdn.microsoft.com/en-us/library/8fskxacy.aspx 
This shouldn't be too hard to support, right? We could, in theory, just use the {.importc: "____".}?

**Comment by Araq** [comment]
Seriously? ``#def``  vs ``#define`` is like the first point in c2nim's slim documentation.
