### ISSUE TITLE
Is this a valid pre-processor declaration?

### ISSUE THREAD

**Issue by jjzazuet** [nim-lang/c2nim#69]
Hi. Suppose I'm trying to wrap a `test.h` header file with this declaration (in the real header I'm trying to wrap, this is one of FMOD's reverb presets):

```
#define FMOD_PRESET_LIVINGROOM       {   500,    3,   4, 5000,  10, 100, 100, 250, 0,   160,  58, -19.0f }
```

If I try to translate using:

```
c2nim --debug test.h
```

I get this error:

```
opt/fmodstudioapi10804linux/api/lowlevel/inc/test.h(1, 45) Error: did not expect {
```

Now, if I turn the `#define` into a `#def`, `c2nim` will translate, but `test.nim` will be empty.

I'm trying to understand `c2nim`'s documentation, but I'm not sure if I'm doing something wrong.

Any thoughts or suggestions are appreciated. Thanks!

**Comment by Varriount** [comment]
It's a valid construct, however c2nim doesn't currently support it.

**Comment by Araq** [comment]
This now compiles and produces a tuple literal. As it should.
