### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by abhi18av** [nim-lang/c2nim#76]
Hello @nim-lang-team

I am experimenting with `nim` and so far I'm quite liking it. I decided to convert some c code to nim but the `c2nim` tool raises errors on `--version` or `--help` 

```sh
> c2nim --help
zsh: exec format error: c2nim

```

Am I not using it right, or is this a bug?

**Comment by Araq** [comment]
That means c2nim is not in your PATH.
