### ISSUE TITLE
CPP std::function support

### ISSUE THREAD

**Issue by codyebberson** [nim-lang/c2nim#83]
c2nim appears to not support ```std::function```.

Example:
```cpp
#include <functional>
#include <iostream>

typedef std::function<void(void)> Foo;

void Bar(void) {
    std::cout << "Hello world!" << std::endl;
}

int main() {
    Foo test = Bar;
    test();
    return 0;
}
```

c2nim output:
```
$ c2nim --version
0.9.12
$ c2nim --cpp test.cpp
test.cpp(4, 34) Error: '> [end of template]' expected
```

```std::function``` is a function wrapper, which can contain both traditional C function pointers and also callable objects.

For a first approximation, treating ```std::function``` as a function pointer may be sufficient.

Suggested c2nim output:
```nim
type
  Foo* = proc ()

proc Bar*()

proc main*(): cint
```

FWIW, I encountered this when experimenting with c2nim and the [AWS C++ SDK](https://github.com/aws/aws-sdk-cpp), which uses ```std::function``` extensively.

**Comment by Araq** [comment]
Fixed but can be improved further.
