### ISSUE TITLE
Nim and C files with same name -- foo.c/foo.nim -> foo.o twice

### ISSUE THREAD

**Issue by pb-cdunn** [nim-lang/c2nim#87]
If I have
```
{.compile: "../subrepo/foo/bar.c".}
```
in `./bar.nim`, generated from `../subrepo/foo/bar.h`, then I get two files called `bar.o` in `nimcache/`.

Well actually, those clobber each other, and I get duplicate symbols because the linker sees `bar.o` twice.

I avoid the problem by renaming `bar.nim` to `Bar.nim` (or anything else).

In some sense this is a problem with the `compile` pragma in Nim, but it occurs with simple use of **c2nim**.

**Comment by Araq** [comment]
Oh really? c2nim does not generate ``{.compile: "../subrepo/foo/bar.c".}``. :P

**Comment by Araq** [comment]
This is not a c2nim bug.

**Comment by pb-cdunn** [comment]
Sure, but how do we build what c2nim generates? We need to compile the original C file too.

If this is a compile-pragma problem, should I re-file in **Nim**?
