### ISSUE TITLE
C++ complex templates fail to parse

### ISSUE THREAD

**Issue by ratiotile** [nim-lang/c2nim#91]
Produces `Error: '> [end of template]' expected`

This is probably related to issue #83 `std::function<void(void)>` - due to not recognizing function signature
`std::function<_PARAM(_PARAM,_PARAM)> pred;`
 `template<class T, int U> class Foo;`  - due to non-type argument
`template<class T, class HashT = std::hash<int>> class Filter;` due to '=' default arg

**Comment by ratiotile** [comment]
Seems like c2nim parses up to the left parens, and knows about std::function.
```
std::function<_PARAM(_PARAM,_PARAM)> pred;
                    ^
result function[_PARAM]
token pxParLe
Error: '> [end of template]' expected
````

**Comment by ratiotile** [comment]
More examples of failed parses:
`template <class T, class HashT = std::hash<int>>`
`template<typename T, int Scale = 1>`
The type-constraint with default arg is a [C++20 feature](https://en.cppreference.com/w/cpp/language/template_parameters)

**Comment by Araq** [comment]
Fixed but can be improved further.
