### ISSUE TITLE
number 18446744073709551615 out of valid range

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/c2nim#93]
As far as I understand, the following should be ignored by c2nim, but it's not. Moreover, the literal is a valid C value.
```c
// test.h
#ifndef C2NIM
#define CASS_UINT64_MAX 18446744073709551615ULL
#endif
```
```
Users/yglukhov/test.h(2, 45) Error: number 18446744073709551615 out of valid range
```

**Comment by Araq** [comment]
Lexing step is not skipped in an ``ifndef C2NIM``  section...
